### ISSUE TITLE
CPLEX conda cloud problem on OSX

### ISSUE THREAD

**Issue by vdbedem** [ExcitedStates/qfit_ligand#1]
Installing qFit-ligand with 

    conda install -c IBMDecisionOptimization docplex cplex

works fine on linux, but it does require a small change in setup.py:

    install_requires=['numpy', 'scipy', 'cvxopt', 'cplex']

to

    install_requires=['numpy', 'scipy', 'cvxopt', 'docplex']

However, installation fails on OSX (High Sierra). On execution of qfit_ligand after going through all the steps, it seems that cvxopt references an older version of libgfortran (libgfortran.2):

    File "/Applications/miniconda2/lib/python2.7/site-packages/cvxopt/__init__.py", line 32, in <module>
    import cvxopt.base
    ImportError: dlopen(/Applications/miniconda2/lib/python2.7/site-packages/cvxopt/base.so, 2): 
    Library not loaded: /usr/local/lib/libgfortran.2.dylib
    Referenced from: /Applications/miniconda2/lib/libopenblasp-r0.2.14.dylib
    Reason: image not found

Anyone seen the same issue?

**Comment by latrocinia** [comment]
On MacOSX cvxopt needs to be installed with pip, *NOT* with conda. Even on Linux it is advised to install via pip as the version is higher. However on Mac I noticed it breaks it, cause it misses some shared library. So I think that is what you are running up against. cplex does need to be installed with conda though.

I'm not sure why docplex is added? Could you elaborate on that? 

To install on Mac

    conda install -c IBMDecisionOptimization numpy scipy cplex
    pip install cvxopt
    git clone https://github.com/excitedstates/qfit_ligand
    cd qfit_ligand
    python setup.py install

qfit_ligand is running smoothly on my Mac with High Sierra after these installations.

On Linux

    conda install -c IBMDecisionOptimization numpy scipy cplex cvxopt
    git clone https://github.com/excitedstates/qfit_ligand
    cd qfit_ligand
    python setup.py install
    
We might consider putting qfit_ligand on pypi so it can be installed with pip, or maybe anaconda.

**Comment by vdbedem** [comment]
Got it. Thanks! 

Not sure why docplex was added. I took that from the installation instructions of CPLEX. If qFit_ligand works without, even better!

Would be great to put qfit_ligand on pypi. Can you make that work?

**Comment by latrocinia** [comment]
I don't think it will work by putting it on pypi or conda. 

For pypi: cplex is not available via pip, so no point putting it there

for conda: its sort of the same reason, but a bit more complex. I actually found the highest cvxopt version on conda, its on the conda-forge channel. But cplex is on the ibmdecisionoptimization channel. Conda strongly advises to put software in a channel that has all dependencies, cause if one of the channels is not part of the default channels, the installation wont work.

So I think its best to keep distributing it on GitHub.

**Comment by vdbedem** [comment]
Disappointing that we can’t distribute qFit-ligand through pypi or conda. But I agree, Github will work.

Thanks!

Henry
